name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  macOS:
    name: macOS
    runs-on: macos-12
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.2.0
      - name: Test
        run: swift test --enable-code-coverage
      - name: Export code coverage in lcov format
        run: xcrun llvm-cov export -format="lcov" -instr-profile .build/debug/codecov/default.profdata .build/debug/CodecovDemoPackageTests.xctest/Contents/MacOS/CodecovDemoPackageTests > coverage.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: coverage.lcov
